const enhancedPromptExamples = 
[
    {
        "provided": "Create a detailed, full-body portrait of a female precocious physicist in their late thirties who looks to be of Southeast Asian heritage in a epic fantasy setting",
        "enhanced": "A full-body portrait of a female physicist in her late thirties with Southeast Asian heritage, standing confidently in an epic fantasy setting. She has a curious, sharp expression and is dressed in a blend of modern and fantasy-inspired attire. Her lab coat is adorned with glowing runes, and underneath she wears practical adventurer’s clothes with hints of intricate embroidery. Her long black hair is tied up in a practical bun with a few loose strands falling around her face. She holds a glowing orb of energy in one hand, which is radiating with vibrant light, while her other hand rests on a leather-bound book strapped to her waist. In the background, there are towering fantastical structures—spires and floating islands with a mix of ancient and futuristic elements, connected by glowing bridges of energy. The sky above is a swirl of colors, suggesting magical forces at play."
    }, 
    {
        "provided": "Create an awesome, epic and cool fantasy digital image of a male supportive scout thirty-something who looks to be of Eastern European heritage in a fairy tale fantasy setting.",
        "enhanced": "A cool and epic fantasy digital image of a male scout in his thirties with Eastern European heritage, set in a fairy tale fantasy setting. He has a supportive, loyal expression and is dressed in rugged but stylish adventurer’s gear, with a fur-lined cloak and light armor suited for stealth. He holds a bow slung over his shoulder and carries a quiver of arrows. His light brown hair is tied back, and his sharp eyes scan the surroundings as if watching over his companions. The background features an enchanted forest with towering, twisted trees, glowing flowers, and soft, magical light filtering through the canopy. In the distance, there are mystical creatures and a distant fairy-tale castle perched on a hill, blending seamlessly into the otherworldly landscape."
    }, 
    {
        "provided": "Create an awesome, epic and cool fantasy digital image of a male diplomatic trader in their late thirties who looks to be of Scandinavian heritage in a high fantasy setting.",
        "enhanced": "An epic fantasy digital image of a male diplomatic trader in his late thirties with Scandinavian heritage, set in a high fantasy world. He has a calm, strategic expression, with long blond hair tied neatly, a trimmed beard, and piercing blue eyes. Dressed in elegant, rich attire with furs and ornate embroidery, he wears a long coat with symbols of his trade guild. A ledger is tucked into his belt, and in one hand he holds a trade agreement scroll. His other hand rests on a staff with an intricate jewel embedded at the top. The background features a grand marketplace with towering, fantastical structures, exotic goods, and magical creatures walking among traders from all lands. The sky is filled with floating airships, and the atmosphere is vibrant, showcasing the diplomatic role of the trader in this high fantasy world."
    }, 
    {
        "provided": "A fantasy image of a male insightful explorer seventy-something who looks to be of African heritage in a science fantasy setting.",
        "enhanced": "A fantasy image of a male explorer in his seventies with African heritage, set in a science fantasy world. He has a wise and insightful expression, with silver hair and a weathered face that speaks of countless adventures. Dressed in a mix of futuristic gear and worn-out adventurer’s clothing, he carries a high-tech staff with glowing elements and a bag filled with mysterious artifacts. The background is a surreal science fantasy landscape, with towering crystalline structures, alien flora, and floating islands. Strange celestial bodies hang in the sky, and there’s a distant starship hovering in the atmosphere, highlighting the explorer’s journey across the stars."
    },
    {
        "provided": "A fantasy image of a male impartial singer in their mid-thirties who looks to be of Caucasian heritage in a traditional fantasy setting.",
        "enhanced": "A fantasy image of a male singer in his mid-thirties with Caucasian heritage, set in a traditional fantasy world. He has an impartial, calm demeanor with short brown hair and a trimmed beard. Dressed in elegant minstrel attire, his clothing is adorned with musical symbols and intricate embroidery. He holds a beautifully crafted lute in one hand and stands in a medieval village square, surrounded by an enchanted forest and stone buildings. The background is filled with vibrant market stalls, and a distant castle can be seen on a hill. The atmosphere is serene, with soft magical lights illuminating the scene as he prepares to perform."
    },
    {
        "provided": "A male idealistic quantum physicist teen who looks to be of Western European heritage in a quantum reality sci-fi setting.",
        "enhanced": "A digital fantasy image of a male quantum physicist teen with Western European heritage, set in a quantum reality sci-fi world. He has an idealistic and curious expression, with short brown hair and bright eyes full of wonder. He’s wearing a futuristic lab coat with glowing quantum symbols and tech-infused gadgets on his wrists. The background depicts a quantum reality with floating particles, energy fields, and shifting geometric shapes, as if the laws of physics are being bent. Complex data and holographic equations float in the air around him, suggesting his deep focus on unraveling the mysteries of the universe. The scene is illuminated by neon and soft glowing lights from the quantum phenomena surrounding him."
    },
    {
        "provided": "A male mysterious void miner in their late twenties who looks to be of Eastern European heritage in a time travel sci-fi setting.",
        "enhanced": "A digital sci-fi image of a male void miner in his late twenties with Eastern European heritage, set in a time travel sci-fi world. He has a mysterious expression, with short dark hair, stubble, and intense eyes that reflect the harshness of space. He wears a rugged, high-tech spacesuit designed for mining in the void, with glowing elements and a sleek, utilitarian design. His suit is slightly worn, showing signs of countless journeys across time and space. The background is a surreal time travel setting, with fragmented realities, floating rocks, and distant stars blending into a swirling void. Ancient ruins and futuristic structures coexist, hinting at the miner's passage through different eras. The lighting is eerie, with shifting hues and shadows, enhancing the sense of mystery around the character."
    },
    {
        "provided": "A female resourceful galactic archivist sixty-something who looks to be of Mediterranean heritage in a mecha sci-fi setting.",
        "enhanced": "A digital sci-fi image of a female galactic archivist in her sixties with Mediterranean heritage, set in a mecha sci-fi world. She has a resourceful and determined expression, with short silver hair and sharp, intelligent eyes. Dressed in a sleek, futuristic uniform with intricate technological details, she carries a data pad in one hand and wears a tool belt filled with various high-tech devices. The setting is a grand, high-tech archive filled with massive digital storage units, holographic screens, and towering mech robots assisting in data retrieval. The background features a blend of futuristic technology and intricate architecture, with a neon glow illuminating the scene. The archivist is surrounded by floating holographic data, showcasing her control over vast amounts of knowledge."
    },
    {
        "provided": "A male unyielding botanist in their late twenties who looks to be of African heritage in a fairy tale fantasy setting.",
        "enhanced": "A digital fantasy image of a male botanist in his late twenties with African heritage, set in a fairy tale fantasy setting. He has an unyielding and determined expression, with short curly hair and a focused gaze. Dressed in a mix of practical and fantasy-inspired attire, he wears a long tunic with nature-themed embroidery and carries tools for tending plants. The background is an enchanted forest, filled with glowing, magical flora and towering trees with intricate, vine-covered trunks. The botanist is surrounded by vibrant, oversized flowers and mystical plants that pulse with energy, emphasizing his role as a protector of the natural world. Soft light filters through the trees, illuminating his work and creating a serene, magical atmosphere."
    },
    {
        "provided": "A fantasy image of a male sullen florist in their forties who looks to be of East Asian heritage in a historical fantasy setting.",
        "enhanced": "A fantasy image of a female florist in her forties with East Asian heritage, set in a historical fantasy world. She has a sullen, melancholic expression, with long, dark hair tied back loosely and delicate facial features that reflect years of contemplation. She wears traditional, flowing garments with subtle floral patterns, hinting at her deep connection with her craft. She stands behind a wooden stall filled with an array of intricate and magical flowers, each one glowing softly or shimmering with enchanted qualities. The background is a historical fantasy setting, with ancient stone buildings and cobblestone streets, bathed in soft twilight. The atmosphere is serene yet filled with a hint of sorrow, as she quietly tends to her magical flowers under the fading light."
    }
]

module.exports = enhancedPromptExamples;